# Generated by Django 3.1.1 on 2021-02-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_categorie_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='size',
            field=models.CharField(choices=[('small', 'small'), ('large', 'large')], default='small', max_length=5),
        ),
    ]
