# Generated by Django 3.1.1 on 2021-04-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
