# Generated by Django 3.1.1 on 2021-05-18 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='store.size'),
            preserve_default=False,
        ),
    ]
